version: '2.1'
services:
  nginx:
    image: nginx:1.13
    depends_on:
      - phpfpm
    environment:
      NGINX_PORT: "80"
    ports:
      - "8151:80"
    volumes:
      - ./:/project
      - ./src/web/web.conf:/etc/nginx/conf.d/default.conf
  phpfpm:
    build: ./src/web/
    environment:
      INTERNAL_API_HOST: "nginx:80"
      API_HOST: "localhost:8151"
      PROJECT_PATH: "/project"
      BUILD_PATH: "/project/build"
      DIST_PATH: "/project/dist"
      DB_FILE: "/project/build/pokedex.sqlite"
    volumes:
      - ./:/project
  importer_showdown:
    build: ./src/importers/showdown/
    environment:
      PROJECT_PATH: "/project"
      BUILD_PATH: "/project/build"
      SOURCES_PATH: "/project/vendor/pokemon-showdown"
    volumes:
      - ./:/project
  importer_veekun:
    build: ./src/importers/veekun/
    environment:
      PROJECT_PATH: "/project"
      SOURCES_PATH: "/project/vendor/veekun-pokedex"
    volumes:
      - ./:/project