version: '2.1'
services:
  data:
    build: ./src/data/
    environment:
      APP_PUBLIC_PATH: "/project/src/data/api/"
      PROJECT_PATH: "/project"
      BUILD_PATH: "/project/build"
      DIST_PATH: "/project/dist"
      DB_FILE: "/project/build/pokedex.sqlite"
      APP_HOST: "0.0.0.0"
      APP_PORT: "8151"
    ports:
      - "8151:8151"
    volumes:
      - ./:/project
  pokemon_showdown:
    build: ./src/pokemon-showdown/
    environment:
      PROJECT_PATH: "/project"
      BUILD_PATH: "/project/build"
      SOURCES_PATH: "/project/vendor/pokemon-showdown"
    volumes:
      - ./:/project
  veekun_pokedex:
    build: ./src/veekun-pokedex/
    environment:
      PROJECT_PATH: "/project"
      SOURCES_PATH: "/project/vendor/veekun-pokedex"
    volumes:
      - ./:/project