version: '2.1'
services:
  setup:
    build: ./src/setup/
    environment:
      PROJECT_PATH: "/project"
      BUILD_PATH: "/project/build"
      DIST_PATH: "/project/dist"
    volumes:
      - ./:/project
    healthcheck:
      test: ["CMD", "php", "/project/src/setup/healthcheck.php"]
      interval: 1m30s
      timeout: 15s
      retries: 3
  data_transformer:
    build: ./src/data-transformer/
    environment:
      PROJECT_PATH: "/project"
      BUILD_PATH: "/project/build"
      DIST_PATH: "/project/dist"
      DB_FILE: "/project/vendor/veekun-pokedex/pokedex/data/pokedex.sqlite"
    volumes:
      - ./:/project
    depends_on:
      setup:
        condition: service_healthy
      pokemon_showdown:
        condition: service_started
      veekun_pokedex:
        condition: service_started
  pokemon_showdown:
    build: ./src/pokemon-showdown/
    environment:
      PROJECT_PATH: "/project"
      BUILD_PATH: "/project/build"
      SOURCES_PATH: "/project/vendor/pokemon-showdown"
    volumes:
      - ./:/project
    depends_on:
      setup:
        condition: service_healthy
  veekun_pokedex:
    build: ./src/veekun-pokedex/
    environment:
      SOURCES_PATH: "/project/vendor/veekun-pokedex"
    volumes:
      - ./:/project
    depends_on:
      setup:
        condition: service_healthy